# nolint start: object_name
#
# General modules =============================================================
# These are nested within other modules
#
#' Server function for building and formatting the All LA table in a Shiny module.
#'
#' @param id A unique identifier for the module. This is used to namespace
#'   inputs and outputs in the server function.
#' @param filtered_bds A reactive expression that returns a filtered data frame
#'   containing LA data. This data frame should be structured to include columns
#'   like `LA Number`, `LA and Regions`, and relevant year data.
#' @param la_names_bds A character vector containing the names of the local
#'   authorities (LAs) to be included in the table. This is used to filter the
#'   data based on specific LAs.
#'
#' @return A Shiny module server function that creates a reactive expression
#'   for generating the formatted All LA table. This table includes calculations
#'   for changes from previous years, ranks based on indicator polarity, and
#'   formats the data into a user-friendly wide format.
#'
#' @details The function performs the following operations:
#'   - Selects relevant columns from the filtered data.
#'   - Calculates the difference between values from the last two years.
#'   - Determines the polarity of the indicator.
#'   - Calculates rankings for local authorities based on values and polarity.
#'   - Converts the long format data to wide format and joins the ranking information.
#'   - Formats the table with pretty number formatting.
#'
#' @examples
#' # Example usage in server
#' Build_AllLATableServer("la_table", filtered_data(), la_names)
#'
Build_AllLATableServer <- function(id, filtered_bds, la_names_bds) {
  moduleServer(id, function(input, output, session) {
    # All LA formatted table
    reactive({
      # All LAs long data
      all_la_long <- filtered_bds() |>
        dplyr::select(`LA Number`, `LA and Regions`, Years, Years_num, values_num, Values)

      # Difference between last two years
      all_la_diff <- all_la_long |>
        calculate_change_from_prev_yr()

      # Get polarity of indicator
      indicator_polarity <- filtered_bds() |>
        pull_uniques("Polarity")

      # Get latest rank, ties are set to min & NA vals to NA rank
      all_la_ranked <- filtered_bds() |>
        filter_la_regions(la_names_bds, latest = TRUE) |>
        dplyr::mutate(
          Rank = dplyr::case_when(
            indicator_polarity %notin% c("High", "Low") ~ "-",
            is.na(values_num) ~ NA,
            # Rank in descending order
            indicator_polarity == "High" ~ as.character(
              rank(-values_num, ties.method = "min", na.last = TRUE)
            ),
            # Rank in ascending order
            indicator_polarity == "Low" ~ as.character(
              rank(values_num, ties.method = "min", na.last = TRUE)
            )
          )
        ) |>
        dplyr::select(`LA and Regions`, Rank)

      # Convert to wide format and join rank column
      all_la_long |>
        rbind(all_la_diff) |>
        tidyr::pivot_wider(
          id_cols = c("LA Number", "LA and Regions"),
          names_from = Years,
          values_from = values_num,
        ) |>
        dplyr::left_join(all_la_ranked, by = "LA and Regions")
    })
  })
}


#' UI function for displaying the name of the All LA table in a Shiny module.
#'
#' @param id A unique identifier for the module. This is used to namespace
#'   inputs and outputs in the UI.
#'
#' @return A UI output element that displays the name of the All LA table,
#'   generated by the server function.
#'
#' @examples
#' # Example usage in UI
#' Get_AllLATableNameUI("table_name")
#'
Get_AllLATableNameUI <- function(id) {
  ns <- NS(id)

  shiny::uiOutput(ns("table_name"))
}


#' Server function for retrieving and rendering the name of the All LA table.
#'
#' @param id A unique identifier for the module, matching the UI id.
#' @param filtered_bds A reactive expression that returns a filtered data frame
#'   containing LA data. This data frame should include a column named
#'   "Chart_title" from which the title is extracted.
#'
#' @return A Shiny module server function that sets up the logic to pull and
#'   render the name of the All LA table based on the filtered data.
#'
#' @details The function extracts the unique chart title from the filtered data
#'   and renders it as a UI output. This is useful for dynamically displaying
#'   the title of the table based on user inputs or selections.
#'
#' @examples
#' # Example usage in server
#' Get_AllLATableNameServer("table_name", filtered_data())
#'
Get_AllLATableNameServer <- function(id, filtered_bds) {
  moduleServer(id, function(input, output, session) {
    # Pull chart title
    output$table_name <- shiny::renderUI({
      filtered_bds() |>
        pull_uniques("Chart_title")
    })
  })
}


#' UI function for creating the All Local Authorities table layout in a Shiny
#' module.
#'
#' @param id A unique identifier for the module. This is used to namespace
#'   inputs and outputs in the UI.
#'
#' @return A UI layout consisting of tabs for viewing tables and downloading
#'   data. It includes the All LA table name, the Local Authorities table,
#'   the Regions table, and a download section for selecting file types.
#'
#' @details The UI is structured using `bslib::navset_card_tab` with two
#'   main panels: one for displaying tables and another for downloading data.
#'   Each table is separated by a styled border for better visibility.
#'
#' @examples
#' # Example usage in UI
#' AllLA_TableUI("all_la_table")
#'
AllLA_TableUI <- function(id) {
  ns <- NS(id)

  div(
    class = "well",
    style = "overflow-y: visible;",
    bslib::navset_tab(
      id = "all_la_table_tabs",
      bslib::nav_panel(
        "Tables",
        bslib::card(
          bslib::card_header(
            Get_AllLATableNameUI(ns("table_name")),
            style = "text-align: center;"
          ),
          bslib::card_header("Local Authorities"),
          with_gov_spinner(
            reactable::reactableOutput(ns("la_table")),
            size = 3
          ),
          div(
            # Add black border between the tables
            style = "border-top: 2px solid black; padding-top: 2.5rem;",
            bslib::card_header("Regions"),
            with_gov_spinner(
              reactable::reactableOutput(ns("region_table")),
              size = 1.6
            )
          )
        )
      ),
      bslib::nav_panel(
        "Download data",
        file_type_input_btn(ns("file_type")),
        Download_DataUI(ns("all_download"), "All Geographies Table"),
        Download_DataUI(ns("la_download"), "LA Table"),
        Download_DataUI(ns("region_download"), "Region Table")
      )
    )
  )
}


#' Server function for managing the All Local Authorities table logic in a
#' Shiny module.
#'
#' @param id A unique identifier for the module, matching the UI id.
#' @param app_inputs A reactive list containing user selections and inputs
#'   for filtering and generating tables.
#' @param bds_metrics A data frame or reactive expression containing BDS metrics
#'   to be used in filtering and creating tables.
#' @param la_names_bds A vector of local authority names to filter the tables.
#'
#' @return A Shiny module server function that handles data processing and
#'   table rendering for local authorities and regions. It also manages the
#'   download functionality for both tables.
#'
#' @details This server function filters the BDS data based on user inputs,
#'   constructs tables for local authorities and regions, and sets up
#'   download handlers for exporting data in the selected format. It includes
#'   reactive expressions for updating tables whenever relevant inputs change.
#'
#' @examples
#' # Example usage in server
#' AllLA_TableServer("all_la_table", app_inputs, bds_metrics, la_names_bds)
#'
AllLA_TableServer <- function(id, app_inputs, bds_metrics, la_names_bds) {
  moduleServer(id, function(input, output, session) {
    # Filter for selected topic and indicator
    filtered_bds <- BDS_FilteredServer(
      "filtered_bds",
      app_inputs,
      bds_metrics
    )

    # Get table name ----------------------------------------------------------
    Get_AllLATableNameServer(
      "table_name",
      filtered_bds
    )

    # Get all LA formatted table
    all_la_table <- Build_AllLATableServer(
      "all_la_table",
      filtered_bds,
      la_names_bds
    )

    # All geographies table download ------------------------------------------
    Download_DataServer(
      "all_download",
      reactive(input$file_type),
      reactive(all_la_table()),
      reactive(c(app_inputs$indicator(), "All-Geographies"))
    )

    # All LA Level LA table ---------------------------------------------------
    output$la_table <- reactable::renderReactable({
      # Filter for LAs and arrange by alphabetical order
      all_la_la_table <- all_la_table() |>
        filter_la_data_all_la(la_names_bds)

      # Output table
      dfe_reactable(
        all_la_la_table,
        # Create the reactable with specific column alignments
        columns = utils::modifyList(
          format_num_reactable_cols(
            all_la_la_table,
            get_indicator_dps(filtered_bds()),
            num_exclude = "LA Number",
            categorical = "Rank"
          ),
          set_custom_default_col_widths()
        ),
        rowStyle = function(index) {
          highlight_selected_row(index, all_la_la_table, app_inputs$la(), "LA")
        },
        pagination = FALSE
      )
    })

    # LA table download -------------------------------------------------------
    Download_DataServer(
      "la_download",
      reactive(input$file_type),
      reactive(filter_la_data_all_la(all_la_table(), la_names_bds)),
      reactive(c(app_inputs$indicator(), "All-LAs-Local-Authorities"))
    )

    # All LA Level Region table -----------------------------------------------
    output$region_table <- reactable::renderReactable({
      # Filter and prepare Region table
      all_la_region_table <- all_la_table() |>
        # Keep only Regions and England (remove London Inner/Outer with all NAs)
        dplyr::filter(
          `LA and Regions` %notin% la_names_bds,
          !(`LA and Regions` %in% c("London (Inner)", "London (Outer)") &
            # Sums number of non-NA cols (left of LA and Regions) and checks if = 0
            rowSums(!is.na(dplyr::select(all_la_table(), -c(`LA Number`, `LA and Regions`)))) == 0)
        ) |>
        # Replace Rank with a blank col
        dplyr::mutate(Rank = "") |>
        dplyr::rename(` ` = "Rank") |>
        dplyr::arrange(`LA Number`) |>
        dplyr::rename("Region" = `LA and Regions`)

      # Get region of LA
      all_la_region <- stat_n_la |>
        dplyr::filter(`LA Name` == app_inputs$la()) |>
        pull_uniques("GOReg") |>
        clean_ldn_region(filtered_bds())

      # Output table
      dfe_reactable(
        all_la_region_table,
        # Create the reactable with specific column alignments
        columns = utils::modifyList(
          format_num_reactable_cols(
            all_la_region_table,
            get_indicator_dps(filtered_bds()),
            num_exclude = "LA Number",
            categorical = "Rank"
          ),
          set_custom_default_col_widths()
        ),
        rowStyle = function(index) {
          highlight_selected_row(index, all_la_region_table, all_la_region, "Region")
        },
        pagination = FALSE
        # class = "hidden-column-headers"
      )
    })

    # Region table download ---------------------------------------------------
    Download_DataServer(
      "region_download",
      reactive(input$file_type),
      reactive(filter_region_data_all_la(all_la_table(), la_names_bds)),
      reactive(c(app_inputs$indicator(), "All-LAs-Regions"))
    )
  })
}

# nolint end
